version: 2.1

workflows:
  sample:
    jobs:
      - recurr
nightly:
  triggers:
    - schedule:
        cron: 0 17 * * 1-5

jobs:
  recurr:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Clone
          command: git clone git@github.com:revanthstrakz/recurr.git
      - run:
          name: Bang
          command: ls recurr
      - run:
          name: permissions
          command: chmod a+x recurr/ini.sh 
      - run:
          name: Bang
          command: /recurr/ini.sh


