version: 2.1

workflows:
  sample:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Clone
          command: git clone git@github.com:revanthstrakz/recurr.git
      - run:
          name: cd recurr
          command: cd recurr
      - run:
          name: permissions
          command: chmod a+x ini.sh
      - run:
          name: Bang
          command: ./ini.sh


